### ISSUE TITLE
Publisher and Year are mixed up in TEI header processing

### ISSUE THREAD

**Issue by tarahmarie** [jdmartin/gutenberg-text-splitter#17]
<img width="830" alt="Screen Shot 2022-06-03 at 3 28 23 PM (2)" src="https://user-images.githubusercontent.com/1920330/171874671-0294aeb3-69ef-40e1-88ea-92f9c093d8ea.png">

**Comment by jdmartin** [comment]
Whoops!  Thanks for letting me know.  This has been fixed by #18, which is merged into main and available as release [0.7.1](https://github.com/jdmartin/gutenberg-text-splitter/releases/tag/0.7.1)
