### ISSUE TITLE
offer option to name chapter files with year of pub and title

### ISSUE THREAD

**Issue by tarahmarie** [jdmartin/gutenberg-text-splitter#25]
choose elements with which to name files, w option to have not just "chapter_1" but "1897-dracula-chapter_1" or similar

**Comment by jdmartin** [comment]
Will investigate.  Changes like this would require some refactoring of your thesis code, too.  Might work fine if the name were '1897_dracula_chapter_1' as the thesis code splits on '-' and not '_'.

**Comment by jdmartin** [comment]
I think this was addressed by #29.  Feel free to reopen, if we're not quite there...
