### ISSUE TITLE
May want to use the HTML5 versions

### ISSUE THREAD

**Issue by eshellman** [jdmartin/gutenberg-text-splitter#32]
for example instead of https://www.gutenberg.org/files/68033/68033-h/68033-h.htm, use https://www.gutenberg.org/cache/epub/68033/pg68033-images.html.utf8

These are guaranteed (more or less) to be easily parseable UTF8 HTML5 files, and will soon have marked boilerplate section which will be much easier to deal with.

**Comment by jdmartin** [comment]
Thanks for this!  I agree that this would be a good change and will merge a fix.  Excited to hear about forthcoming, easily identified boilerplate. (Not that it's so hard already, but anything predictable is great with a tool like this...)  😄
