### ISSUE TITLE
So odd - some files not being processed

### ISSUE THREAD

**Issue by tarahmarie** [jdmartin/gutenberg-text-splitter#35]
<img width="1480" alt="Screen Shot 2022-06-21 at 6 21 24 AM" src="https://user-images.githubusercontent.com/1920330/174809908-e195e14a-3e2d-428a-a1e9-3a2d5d425f4a.png">

See, e.g. Pickwick chapter 22. This may not be anything but an IDE glitch.

**Comment by jdmartin** [comment]
That does seem unlikely. But then again, I wrote it... will investigate.

**Comment by jdmartin** [comment]
@tarahmarie Out of curiosity, could you tell me what values you gave before processing? I can't imagine it should matter, but I want to try to replicate as closely as I'm able.
